force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountUtils.cls
public class AccountUtils {
    public static List<Account>accountsByState(String abbreviatedState){
        return [SELECT Id, Name FROM Account WHERE BillingState =:abbreviatedState];
    }
    public static List<Account> getAccountsByStatus(String status) {
        return [SELECT Id, Name FROM Account WHERE Status__c = :status];
    }

    public static Integer getContactCountByAccountId(Id accountId) {
        return [SELECT COUNT() FROM Contact WHERE AccountId = :accountId];
    }

    public static Boolean isHighPriority(Account acc) {
        if (acc.CustomerPriority__c == 'High') {
            return true;
        }
        return false;
    }
}