force-app/main/default/objects/Application__c/fields/Application_Fee__c.field-meta.xml
<CustomField>
    <fullName>Application_Fee__c</fullName>
    <label>Application Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Postgraduate.recordType-meta.xml
<RecordType>
    <fullName>Postgraduate</fullName>
    <active>true</active>
    <label>Postgraduate</label>
</RecordType>

force-app/main/default/objects/Application__c/recordTypes/Undergraduate.recordType-meta.xml
<RecordType>
    <fullName>Undergraduate</fullName>
    <active>true</active>
    <label>Undergraduate</label>
</RecordType>

force-app/main/default/classes/ApplicationTriggerHandler.cls
public class ApplicationTriggerHandler {
    public static void setFees(List<Application__c> applications){
        Id undergradRtId = Application__c.SObjectType
            .getDescribe()
            .getRecordTypeInfosByDeveloperName()
            .get('Undergraduate')
            .getRecordTypeId();
		Id postgradRtId = Application__c.SObjectType
            .getDescribe()
            .getRecordTypeInfosByDeveloperName()
            .get('Postgraduate')
            .getRecordTypeId();
        
        for(Application__c app : applications){
            if(app.RecordTypeId == undergradRtId){
                app.Application_Fee__c = 1000;
            }
            else if (app.RecordTypeId == postgradRtId){
                app.Application_Fee__c = 2000;
            }
        } 
    }
}