force-app/main/default/objects/Application__c/fields/Application_Fee__c.field-meta.xml
<CustomField>
    <fullName>Application_Fee__c</fullName>
    <label>Application Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Application__c/recordTypes/Postgraduate.recordType-meta.xml
<RecordType>
    <fullName>Postgraduate</fullName>
    <active>true</active>
    <label>Postgraduate</label>
</RecordType>

force-app/main/default/objects/Application__c/recordTypes/Undergraduate.recordType-meta.xml
<RecordType>
    <fullName>Undergraduate</fullName>
    <active>true</active>
    <label>Undergraduate</label>
</RecordType>

force-app/main/default/classes/ApplicationTriggerHandlerTest.cls
@isTest
private class ApplicationTriggerHandlerTest {
    private static Id getRecordTypeId(String developerName) {
        return Application__c.SObjectType
            .getDescribe()
            .getRecordTypeInfosByDeveloperName()
            .get(developerName)
            .getRecordTypeId();
    }
    
    @isTest static void testUndergraduateFee() {
        Application__c app = new Application__c(
            Name = 'Test Undergraduate',
            RecordTypeId = getRecordTypeId('Undergraduate')
        );
        insert app;
        
        app = [ 
            SELECT Application_Fee__c FROM Application__c WHERE Id =:app.Id
        ];
        
        System.assertEquals(1000, app.Application_Fee__c);
    }
    @isTest static void testpostgraduateFee() {
        Application__c app = new Application__c(
            Name = 'Test Postgraduate',
            RecordTypeId = getRecordTypeId('Postgraduate')
        );
        insert app;
        
        app = [ 
            SELECT Application_Fee__c FROM Application__c WHERE Id =:app.Id
        ];
        
        System.assertEquals(2000, app.Application_Fee__c);
    }
}